version: "2"
services:
  app:
    environment:
      - PYTHONUNBUFFERED=0
      - DB_USER=${DB_USER}
      - DB_USER_PASSWORD=${DB_USER_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
    build: .
    links:
      - db
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.app.schedule: "@every 45s"
      ofelia.job-exec.app.command: "task"
    ports:
      - "8888:8888"
  ofelia:
    image: mcuadros/ofelia:latest
    restart: always
    depends_on:
      - app
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  db:
    image: mariadb:latest
    ports:
      - "32000:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
